services:
  # --- Reverse Proxy ---
  nginx-zone3:
    image: nginx:stable-alpine
    container_name: zone3-nginx
    ports:
      - "8083:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - zone3_net
      - shared_network
    depends_on:
      - backend-timeline
      - frontend-retex

  # --- Backend (Mock) ---
  backend-timeline:
    build: ./services/backend-timeline
    container_name: zone3-backend
    environment:
      - MOCK_MODE=true
      - KEYCLOAK_URL=http://keycloak:8080
    networks:
      - zone3_net
      - shared_network
      - traceops
    extra_hosts:
      - "peer0.orgem.traceops.local:host-gateway"
      - "peer0.orgj2.traceops.local:host-gateway"
      - "orderer1.traceops.local:host-gateway"
      - "orderer0.traceops.local:host-gateway"
    env_file:
      - .env
    volumes:
      - ./wallet:/app/wallet:ro
      - ./connection-profiles:/app/connection-profiles:ro

  # --- Frontend (Vue) ---
  frontend-retex:
    build: ./services/frontend-retex
    container_name: zone3-frontend
    networks:
      - zone3_net
      - shared_network

networks:
  zone3_net:
    driver: bridge
  shared_network:
    external: true
    name: zone1_zone1-network
  traceops:
    external: true
    name: traceops
